int main(void);
void handle_timer_interrupt(void);
void timerinit(void);
void init_uart0(void);
void interruptinit(void);
void plic_cap_init(void);
void panic(char *s);
void putachar(char c);
void printstring(const char *s);
void printhex(uint64_t x);
char getachar(void);
void plic_init(void);
int plic_claim(void);
void plic_complete(int irq);
void uartintr(void);
void trapinit(void);
int devintr(void);
void enable_paging(void);
char yield(void);
void* __capability init_pagetable(int proc);
void debug_pagetable(int proc);